### ISSUE TITLE
About negative samples for testing

### ISSUE THREAD

**Issue by vincenttsai2015** [Sweetnow/group-buying-recommendation#7]
Hi,

After resolving the issues of testing execution, I'm wondering if the following error is due to the lack of test.negative.txt. 

![image](https://user-images.githubusercontent.com/13366052/146499690-97aea1c5-5f76-4cb7-b63a-863be9d99841.png)

If so, how can I generate negative samples? Thanks.

**Comment by Sweetnow** [comment]
Are you use your private dataset?

**Comment by Sweetnow** [comment]
If so, you should generate the test.negative.txt by yourself.

The format is described in https://github.com/Sweetnow/group-buying-recommendation/tree/master/datasets.

Due to the file size limitation, the negative sample files corresponding to tune/test.txt will be uploaded to GitHub Releases. Each line of the negative sample files is 999 user_id separated by \t and corresponds to tune/test.txt by line number.

That is, it looks like:
```txt
1	7	5	999	88	77	...		1
...
...

```

You can download the negative sample files for BeiBei in https://github.com/Sweetnow/group-buying-recommendation/releases as reference.

**Comment by vincenttsai2015** [comment]
> Are you use your private dataset?

Yes, I'm using my own dataset (Yelp, Foursquare and Timik) following the formats required for the execution of GBMF/GBGCN.
What does each line in the format of negative sampling for testing (test.negative,txt) mean? Thanks.

**Comment by Sweetnow** [comment]
If so, you should generate the test.negative.txt by yourself.

The format is described in https://github.com/Sweetnow/group-buying-recommendation/blob/master/datasets/readme.md.

Due to the file size limitation, the negative sample files corresponding to tune/test.txt will be uploaded to GitHub Releases. Each line of the negative sample files is 999 user_id separated by \t and corresponds to tune/test.txt by line number.

That is, it looks like:
```txt
1	7	5	999	88	77	...		1
...
...

```

You can download the negative sample files for BeiBei in https://github.com/Sweetnow/group-buying-recommendation/releases as reference.

**Comment by vincenttsai2015** [comment]
> What does each line in the format of negative sampling for testing (test.negative,txt) mean? Thanks.

Does each line in the format of negative sampling for testing (test.negative,txt) represent "[user_id] [item_ids]"? Thanks.

**Comment by Sweetnow** [comment]
No. Let's define P = item and Q = user following my settings. (maybe for you, P = user, Q = item)

In `test.txt`, each line is `[P_pos] [Q_launcher] [Qs_participants]`.

In `test.negative.txt`, each line is `[Qs_neg_launcher]`

In total, it is `[P_pos] [Q_launcher] [Qs_participants] [Qs_neg_launcher]`

**Comment by vincenttsai2015** [comment]
But according to [readme for BeiBei dataset](https://github.com/Sweetnow/group-buying-recommendation/blob/master/datasets/readme.md), shouldn't the format of each line in [valid/invalid/train/tune/test].txt be as follows? 
``` [Q_launcher] [P_pos] [Qs_participants] ```

**Comment by Sweetnow** [comment]
Sorry for mistake...

The correct setting is

P = user, Q = item

the total line is `[P_launcher] [Q_pos] [Ps_participants] [Qs_neg]`

https://github.com/Sweetnow/group-buying-recommendation/blob/270ffd96d4bd8c3470d868084758b912584a2705/GBGCN.py#L452-L465

`self.pos_pairs` is the first two columns in `test.txt`

`self.neg_qs` is the content in `test.negative.txt`

**Comment by vincenttsai2015** [comment]
Therefore, the format should be as follows, right?

1. [valid/invalid/train/tune/test].txt: ``` [P_launcher] [Q_pos] [Ps_participants] ```
2. [tune/test].negative.txt: ``` [Qs_neg]  ``` (or ``` [P_launcher] [Q_pos] [Ps_participants] [Qs_neg] ```?) 

And can the number of negative samples in each line be arbitrary? Thanks.

**Comment by Sweetnow** [comment]
negative.txt should be `[Qs_neg]`.

The number should be the same. Because it will be converted to "matrix”

**Comment by vincenttsai2015** [comment]
> negative.txt should be `[Qs_neg]`.
> 
> The number should be the same. Because it will be converted to "matrix”

So the number for each line can be N (which can be 100, 200, 300, etc.), i.e., every line has N negative samples, right?

**Comment by Sweetnow** [comment]
If you use LeaveOneOutTestDataset, the number of negative samples is coded at https://github.com/Sweetnow/librecframework/blob/64a17ae400aa273f82ffd3ee46f0a0bd1c3dcb40/librecframework/data/dataset.py#L246
and the framework will generate negative sampling file automatically if it dose not exists.

**Comment by Sweetnow** [comment]
It is so long time for me that I have forgotten the details of my codes. Really SORRY!!!

**Comment by vincenttsai2015** [comment]
> It is so long time for me that I have forgotten the details of my codes. Really SORRY!!!

It's OK. Thanks for your reply. It is more clear to know what to do in the next steps. 
Thanks again!!

**Comment by Sweetnow** [comment]
Looking forward to your paper!
